[package]
name = "jwtsign"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib"]

[dependencies]
jsonwebtoken = "8.3.0"
openssl = "0.10.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.2"
ring = "0.16.20"
