name: Publish PyPI Package

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Pip and Rust
        run: |
          python -m pip install --upgrade pip
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable

      - name: Make package
        run: make dist

      - name: Add manylinux wheels
        run: |
          docker run -v $(pwd):/io quay.io/pypa/manylinux_2_28_x86_64 /io/build-wheels.sh
          mv wheelhouse/*.whl dist/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
